name: DailyReadiness
options:
  bundleIdPrefix: com.imprvhealth
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

targets:
  DailyReadiness:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "*.md"
          - ".git/**"
          - "build.sh"
          - "build-and-run.sh"
          - "project.yml"
          - ".github/**"
          - "Info.plist"
          - "BUILD_COMMANDS.md"
          - "SETUP.md"
          - "LOCAL_OPTIONS.md"
          - "REACT_NATIVE_VS_SWIFT.md"
          - "QUICK_START.md"
          - "Tests/**"
          - "SwiftExperiment/**"
          - "JEST_AND_GEMINI_SETUP.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imprvhealth.DailyReadiness
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: "YES"

  DailyReadinessTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: DailyReadiness
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imprvhealth.DailyReadinessTests
        INFOPLIST_FILE: Tests/Info.plist
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

schemes:
  DailyReadiness:
    build:
      targets:
        DailyReadiness: all
        DailyReadinessTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - DailyReadiness
      targets:
        - name: DailyReadinessTests
          parallelizable: true
    archive:
      config: Release

