name: DailyReadiness
options:
  bundleIdPrefix: com.imprvhealth
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

targets:
  DailyReadiness:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "*.md"
          - ".git/**"
          - "build.sh"
          - "build-and-run.sh"
          - "project.yml"
          - ".github/**"
          - "Info.plist"
          - "BUILD_COMMANDS.md"
          - "SETUP.md"
          - "LOCAL_OPTIONS.md"
          - "REACT_NATIVE_VS_SWIFT.md"
          - "QUICK_START.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imprvhealth.DailyReadiness
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: "YES"

schemes:
  DailyReadiness:
    build:
      targets:
        DailyReadiness: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release

