# TEACHING: XcodeGen Configuration
# XcodeGen generates Xcode project files from this YAML.
# Benefits:
# - Project files don't need to be committed (avoid merge conflicts)
# - Configuration is human-readable
# - Easy to add/remove files

name: SwiftExperiment

options:
  bundleIdPrefix: com.suprahuman.experiment
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

# TEACHING: Settings
# Project-level build settings shared by all targets
settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    # Enable strict concurrency checking for Swift 6 readiness
    SWIFT_STRICT_CONCURRENCY: complete

# TEACHING: Targets
# Each target becomes a build product (app, framework, test, etc.)
targets:
  SwiftExperiment:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    # Source files
    sources:
      - path: Sources
        excludes:
          - "**/*.md"
          - "**/.DS_Store"

    # Settings specific to this target
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.suprahuman.experiment.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        SUPPORTS_MACCATALYST: false
        # Amplify requires these entitlements
        CODE_SIGN_ENTITLEMENTS: Resources/SwiftExperiment.entitlements

    # Swift Package Manager dependencies
    dependencies:
      - package: amplify-swift
        products:
          - Amplify
          - AWSCognitoAuthPlugin
          - AWSAPIPlugin

    # Pre/post build scripts
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed. Run: brew install swiftlint"
          fi
        basedOnDependencyAnalysis: false

  # Unit test target
  SwiftExperimentTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: Tests
        excludes:
          - "**/.DS_Store"

    dependencies:
      - target: SwiftExperiment

    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.suprahuman.experiment.tests

# TEACHING: Packages
# Swift Package Manager dependencies
packages:
  amplify-swift:
    url: https://github.com/aws-amplify/amplify-swift.git
    from: "2.0.0"

# TEACHING: Schemes
# Build schemes define how targets are built and run
schemes:
  SwiftExperiment:
    build:
      targets:
        SwiftExperiment: all
        SwiftExperimentTests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: AMPLIFY_LOG_LEVEL
          value: debug
          isEnabled: true
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SwiftExperiment
      targets:
        - name: SwiftExperimentTests
          parallelizable: true
